#!/usr/bin/env python3

import requests
from flask import Flask, request
import configparser

app = Flask(__name__)

@app.route('/metrics', methods=['GET', 'POST'])
def metrics():
    if request.method == "GET":
        config = parse_config()
        url = config['default']['url']
        nodes = get_nodes(url)
        response = get_response(nodes)

        return "\n".join(response) + "\n"


def get_response(nodes):
    response = []
    response.append("# HELP oxidized_status Status of last oxidized backup")
    response.append("# TYPE oxidized_status gauge")
    for node in nodes:
        status = 1 if node['status'] == 'success' else 0
        response.append("oxidized_status{{instance=\"{}\"}} {}".format(node['name'], status))

    return response

def parse_config():
    config = configparser.ConfigParser()
    config.read('oxidized.conf')

    return config

def get_nodes(url):
    r = requests.get(url + '/nodes.json')
    nodes = r.json()

    return nodes 

if __name__ == "__main__":
    app.run(port=5002)

